# -------------------------
# PostgreSQL Database
# -------------------------
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=${SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE:10}
spring.datasource.hikari.minimum-idle=${SPRING_DATASOURCE_HIKARI_MINIMUM_IDLE:2}
spring.datasource.hikari.idle-timeout=${SPRING_DATASOURCE_HIKARI_IDLE_TIMEOUT:300000}
spring.datasource.hikari.max-lifetime=${SPRING_DATASOURCE_HIKARI_MAX_LIFETIME:1800000}
spring.datasource.hikari.connection-timeout=${SPRING_DATASOURCE_HIKARI_CONNECTION_TIMEOUT:30000}
spring.datasource.hikari.validation-timeout=${SPRING_DATASOURCE_HIKARI_VALIDATION_TIMEOUT:5000}

# -------------------------
# JPA
# -------------------------
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# -------------------------
# Flyway
# -------------------------
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=true

# -------------------------
# GraphQL
# -------------------------
spring.graphql.graphiql.path=/graphiql
spring.graphql.graphiql.enabled=true

# -------------------------
# RabbitMQ / CloudAMQP
# -------------------------
spring.rabbitmq.addresses=${CLOUDAMQP_URI}
spring.rabbitmq.ssl.enabled=true
spring.rabbitmq.ssl.algorithm=TLSv1.2
spring.rabbitmq.listener.simple.acknowledge-mode=auto
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.max-attempts=3

# Logging RabbitMQ
logging.level.org.springframework.amqp=DEBUG

# -------------------------
# Server Port
# -------------------------
server.port=${SERVER_PORT:8080}

# Mailgun config
mailjet.api-key=${MAILJET_API_KEY}
mailjet.secret-key=${MAILJET_SECRET_KEY}
mailjet.from-email=${MAILJET_FROM_MAIL}
mailjet.from-name=${MAILJET_FROM_NAME}

# Frontend config
app.frontend.url=${FRONTEND_URL:http://localhost:5173}

